# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/ECE532/Fibonacci_LFSR/Fibonacci_LFSR.cache/wt [current_project]
set_property parent.project_path E:/ECE532/Fibonacci_LFSR/Fibonacci_LFSR.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib E:/ECE532/Fibonacci_LFSR/Fibonacci_LFSR.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ECE532/Fibonacci_LFSR/Fibonacci_LFSR.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files E:/ECE532/Fibonacci_LFSR/Fibonacci_LFSR.srcs/constrs_1/new/const.xdc]


synth_design -top Fibonacci_LFSR -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Fibonacci_LFSR.dcp

catch { report_utilization -file Fibonacci_LFSR_utilization_synth.rpt -pb Fibonacci_LFSR_utilization_synth.pb }
