# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/edit_Fib_LFSR_v1_0.cache/wt [current_project]
set_property parent.project_path C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/edit_Fib_LFSR_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/Fib_LFSR_1.0
  c:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/Fibonacci_LFSR_1.0
  c:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/fibonacci_LFSR_1.0
} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/Fib_LFSR_1.0/hdl/Fibonacci_LFSR.v
  C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/Fib_LFSR_1.0/hdl/Fib_LFSR_v1_0_S00_AXI.v
  C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/warmup_demo/IPs/ip_repo/Fib_LFSR_1.0/hdl/Fib_LFSR_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Fib_LFSR_v1_0 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Fib_LFSR_v1_0.dcp

catch { report_utilization -file Fib_LFSR_v1_0_utilization_synth.rpt -pb Fib_LFSR_v1_0_utilization_synth.pb }
