set_property PACKAGE_PIN J15 [get_ports {switch}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch}]
set_property PACKAGE_PIN G13 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN H17 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]