# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1}]

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}]

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}] {/U0 }]/U0 ]]
