# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/remote_controller/remote_controller.cache/wt [current_project]
set_property parent.project_path C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/remote_controller/remote_controller.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/remote_controller/remote_controller.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/remote_controller/remote_controller.xdc
set_property used_in_implementation false [get_files C:/Users/Neil/Documents/Neil/EngSci/year_4_winter/ECE532/remote_controller/remote_controller.xdc]


synth_design -top remote_controller -part xc7a100tcsg324-1


write_checkpoint -force -noxdef remote_controller.dcp

catch { report_utilization -file remote_controller_utilization_synth.rpt -pb remote_controller_utilization_synth.pb }
